### ISSUE TITLE
Issue in @ToDo in basic.30.operators.logical.js

### ISSUE THREAD

**Issue by Zorigins** [vishalz/hello-js#7]
* @todo Declare variables v15 , v15_value and v15_type
* Assign v15 = "false" && "dog" ; 
* Assign the value of variable v15 to variable v15_value as a string e.g. "40" or "5000" or "true" or "false"
* Assign the type of v15 to v15_type as a string e.g. "number" or "string" or "boolean"

When you declare like so and test,
var v15 = "false" && "dog";
var v15_value = "";

**Comment by vishalz** [comment]
Fixed in v2.9.4
